import React, { useState } from 'react';
import { Link, NavLink } from 'react-router-dom';
import "../styles/Generator.css";

const parseGitHubUrl = (url) => {
  const trimmed = url.trim();
  if (!trimmed) return { isValid: false, owner: '', repo: '' };

  const regex = /^(?:https?:\/\/)?(?:www\.)?github\.com\/([a-zA-Z0-9-._]+)\/([a-zA-Z0-9-._]+)(?:\/.*)?$/;
  const match = trimmed.match(regex);

  if (match) {
    let owner = match[1];
    let repo = match[2];
    
    if (repo.endsWith('.git')) {
      repo = repo.slice(0, -4);
    }
    
    return { isValid: true, owner, repo };
  }

  return { isValid: false, owner: '', repo: '' };
};

const Generator = () => {
  const [repoUrl, setRepoUrl] = useState('');
  const [customInstructions, setCustomInstructions] = useState('');
  const [isGenerating, setIsGenerating] = useState(false);
  const [markdownOutput, setMarkdownOutput] = useState('');
  const [copied, setCopied] = useState(false);
  
  // Validation and animation state
  const [error, setError] = useState('');
  const [shouldShake, setShouldShake] = useState(false);

  const handleUrlChange = (e) => {
    setRepoUrl(e.target.value);
    if (error) {
      setError('');
    }
  };

  const handleGenerate = async () => {
    const trimmedUrl = repoUrl.trim();
    if (!trimmedUrl) {
      setError('Please enter a GitHub repository URL.');
      setShouldShake(true);
      setTimeout(() => setShouldShake(false), 400);
      return;
    }

    const parsed = parseGitHubUrl(trimmedUrl);
    if (!parsed.isValid) {
      setError('Invalid GitHub URL. Expected format: https://github.com/owner/repository');
      setShouldShake(true);
      setTimeout(() => setShouldShake(false), 400);
      return;
    }

    setError('');
    setIsGenerating(true);
    
    const repoTitle = `${parsed.owner}/${parsed.repo}`;
    const repoFolder = parsed.repo;

    try {
      const response = await fetch(`https://api.github.com/repos/${parsed.owner}/${parsed.repo}`);
      if (response.status === 404) {
        setError('Repository not found. Please verify the URL and ensure it is a public repository.');
        setIsGenerating(false);
        setShouldShake(true);
        setTimeout(() => setShouldShake(false), 400);
        return;
      }
    } catch (e) {
      console.warn("Could not verify repository existence, proceeding anyway:", e);
    }

    setTimeout(() => {
      setMarkdownOutput(`# Documentation for: ${repoTitle}\n\n## Overview\nThis documentation was automatically generated by AutoDoc.ai.\n\n## Installation\n\`\`\`bash\ngit clone ${trimmedUrl}\ncd ${repoFolder}\nnpm install\n\`\`\`\n\n## Usage\nBasic usage instructions will appear here once your repository is analyzed.\n\n## API Reference\nAPI documentation will be generated automatically.\n\n## Contributing\nGuidelines for contributions will be populated based on repository analysis.\n`);
      setIsGenerating(false);
    }, 2000);
  };

  const handleCopyCode = () => {
    if (!markdownOutput) return;
    navigator.clipboard.writeText(markdownOutput);
    setCopied(true);
    setTimeout(() => setCopied(false), 2000);
  };

  return (
    <div className="generator-container">
      <nav className="navbar">
        <div className="nav-logo">
          AutoDoc.ai
        </div>
        <ul className="nav-links">
          <li><NavLink to="/">Home</NavLink></li>
          <li><NavLink to="/generator">Generator</NavLink></li>
          <li><NavLink to="/contributors">Contributors</NavLink></li>
        </ul>
      </nav>

      <main className="workspace">
        <div className="control-panel">
          <h2 className="panel-title">Repository Configuration</h2>

          <div className="input-group">
            <label htmlFor="repo-url">GitHub Repository URL</label>
            <input
              id="repo-url"
              type="url"
              placeholder="https://github.com/username/repository"
              value={repoUrl}
              onChange={handleUrlChange}
              className={`text-input ${error ? 'input-error' : ''} ${shouldShake ? 'shake' : ''}`}
            />
            {error && (
              <div className="error-message">
                <span className="error-icon">⚠</span> {error}
              </div>
            )}
          </div>

          <div className="input-group">
            <label htmlFor="custom-instructions">Custom Instructions (Optional)</label>
            <textarea
              id="custom-instructions"
              placeholder="Add any specific requirements or focus areas for the documentation..."
              value={customInstructions}
              onChange={(e) => setCustomInstructions(e.target.value)}
              className="text-textarea"
              rows={5}
            />
          </div>

          <button
            onClick={handleGenerate}
            disabled={isGenerating}
            className="btn btn-primary generate-btn"
          >
            {isGenerating ? (
              <>
                <span className="spinner"></span>
                Generating...
              </>
            ) : (
              'Generate Documentation'
            )}
          </button>
        </div>

        <div className="output-panel">
          <div className="output-header">
            <h3>Generated Documentation</h3>
            {markdownOutput && (
              <button 
                onClick={handleCopyCode} 
                className={`btn btn-copy ${copied ? 'copied' : ''}`}
              >
                {copied ? 'Copied! ✓' : 'Copy Code'}
              </button>
            )}
          </div>
          <pre className="output-content">
            <code>{markdownOutput || '# Your documentation will appear here...'}</code>
          </pre>
        </div>
      </main>
    </div>
  );
};

export default Generator;