import React, { useState } from 'react';
import { Link, NavLink } from 'react-router-dom';
import "../styles/Generator.css";

const Generator = () => {
  const [repoUrl, setRepoUrl] = useState('');
  const [customInstructions, setCustomInstructions] = useState('');
  const [isGenerating, setIsGenerating] = useState(false);
  const [markdownOutput, setMarkdownOutput] = useState('');

  const handleGenerate = () => {
    setIsGenerating(true);
    setTimeout(() => {
      setMarkdownOutput(`# Documentation for: ${repoUrl || 'Repository'}\n\n## Overview\nThis documentation was automatically generated by AutoDoc.ai.\n\n## Installation\n\`\`\`bash\ngit clone ${repoUrl || 'https://github.com/username/repository'}\ncd repository\nnpm install\n\`\`\`\n\n## Usage\nBasic usage instructions will appear here once your repository is analyzed.\n\n## API Reference\nAPI documentation will be generated automatically.\n\n## Contributing\nGuidelines for contributions will be populated based on repository analysis.\n`);
      setIsGenerating(false);
    }, 2000);
  };

  const handleCopyCode = () => {
    navigator.clipboard.writeText(markdownOutput);
  };

  return (
    <div className="generator-container">
      <nav className="navbar">
        <div className="nav-logo">
          AutoDoc.ai
        </div>
        <ul className="nav-links">
          <li><NavLink to="/">Home</NavLink></li>
          <li><NavLink to="/generator">Generator</NavLink></li>
          <li><NavLink to="/contributors">Contributors</NavLink></li>
        </ul>
      </nav>

      <main className="workspace">
        <div className="control-panel">
          <h2 className="panel-title">Repository Configuration</h2>

          <div className="input-group">
            <label htmlFor="repo-url">GitHub Repository URL</label>
            <input
              id="repo-url"
              type="url"
              placeholder="https://github.com/username/repository"
              value={repoUrl}
              onChange={(e) => setRepoUrl(e.target.value)}
              className="text-input"
            />
          </div>

          <div className="input-group">
            <label htmlFor="custom-instructions">Custom Instructions (Optional)</label>
            <textarea
              id="custom-instructions"
              placeholder="Add any specific requirements or focus areas for the documentation..."
              value={customInstructions}
              onChange={(e) => setCustomInstructions(e.target.value)}
              className="text-textarea"
              rows={5}
            />
          </div>

          <button
            onClick={handleGenerate}
            disabled={isGenerating}
            className="btn btn-primary generate-btn"
          >
            {isGenerating ? (
              <>
                <span className="spinner"></span>
                Generating...
              </>
            ) : (
              'Generate Documentation'
            )}
          </button>
        </div>

        <div className="output-panel">
          <div className="output-header">
            <h3>Generated Documentation</h3>
            {markdownOutput && (
              <button onClick={handleCopyCode} className="btn btn-copy">
                Copy Code
              </button>
            )}
          </div>
          <pre className="output-content">
            <code>{markdownOutput || '# Your documentation will appear here...'}</code>
          </pre>
        </div>
      </main>
    </div>
  );
};

export default Generator;